#!/usr/bin/env bash

# dirjump - set marks on directory paths and go back to them
#
# COMMANDS:
#   mark <n> - mark the current directory with letter <n>
#   jump <n> - jump to the directory marked by letter <n>
#   last - jump to the most recently marked directory that isnt
#          the current working one (multiple times toggles between two)
#   list - list all marked directories
#   clear <n> - clear directory with mark <n>
#   clear-all - clear all directory marks


main() {

local MAINDIR="$HOME/.dirjump"

mkdir -p $MAINDIR
touch $MAINDIR/marks

from-mark () {
  
  echo "$(grep "^${1}" $MAINDIR/marks | cut -d' ' -f 2-)"

}

case "$1" in

  mark)
    set -u
    if [[ "$(from-mark $2)" ]]; then
      echo 'mark already exists'
      return 0
    fi
    
    echo "$2 $(pwd)" | cat $MAINDIR/marks - | sort > /tmp/newmarks
    cat /tmp/newmarks > $MAINDIR/marks
    echo "mark $2 set"
  ;;

  jump)
    local TARGET="$(from-mark $2)" 
    if [[ -z "$TARGET" ]]; then
      echo 'no such mark'
      return 0
    fi
    cd "$TARGET"
  ;;

  list)
    cat $MAINDIR/marks
  ;;

  clear)
    if [[ "$2" ]]; then
      sed -i '' "/^$2/d" $MAINDIR/marks
      echo "mark $2 cleared!"
    else
      printf '' > $MAINDIR/marks
      echo 'all marks cleared!'
    fi
  ;;

  mark-or-jump)
    # create if mark doesn't exist
    # mark if jump does exist
    # otherwise list
    if [[ -z "$2" ]]; then
      cat $MAINDIR/marks
      return 0
    fi
    local TARGET="$(from-mark "$2")"
    if [[ "$TARGET" ]]; then
      cd "$TARGET"
    else
      dirjump mark "$2"
    fi
  ;;

esac

}

main "$@"
