-- color scheme
-- require("core.plugin_config.gruvbox")
require("core.plugin_config.catppuccin")
require("core.plugin_config.nvimtree_config")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.barbar")
require("core.plugin_config.lsp_config")
require("core.plugin_config.cmp_config")
