# DEPRECATED - use bash/aliases instead

# You can alwas see what an alias does with `alias <command>`



# | shell |

alias c=clear
alias ll='ls -l'
alias mv='mv -i'
alias cdd="cd $HOME/dotfiles"
alias cdm="cd $HOME/mason"
alias cdp="cd $HOME/mason/programming"
cb() { cd $OLDPWD ; }


# | git |

alias gs='git status'
alias gc='git checkout'
alias glo='git log --oneline'
alias ga='git add'
alias gd='git diff'
alias gt='git commit'
alias gca='git commit --amend'
rrebase() {
  set -u
  
  git checkout $1
  git pull origin $1
  g..
  git rebase $1
  echo 'happy hacking :)'
  set +u
}

# | tmux |
alias t='tmux'

# | nvim |
alias n='nvim'

# | docker compose |
alias dc='docker compose'
# | HOLLYWOOD |
alias hollywood='docker run --rm -it bcbcarl/hollywood'
