# You can alwas see what an alias does with `alias <command>`

# | shell |

alias c=clear
alias ll='ls -l'
alias mv='mv -i'
alias cdd="cd $HOME/dotfiles"
alias cdm="cd $HOME/mason"
cb() { cd $OLDPWD ; }


# | git |

alias gpr='git push origin master'
alias gs='git status'
alias glo='git log --oneline'

# | tmux |
alias t='tmux'
