# You can alwas see what an alias does with `alias <command>`

# | shell |

alias c=clear
alias ll='ls -l'
alias mv='mv -i'
alias cdd="cd $HOME/dotfiles"
alias cdm="cd $HOME/mason"
cb() { cd $OLDPWD ; }


# | git |

alias gs='git status'
alias glo='git log --oneline'
alias ga='git add'
alias gd='git diff'
alias gt='git commit'

# | tmux |
alias t='tmux'

# | nvim |
alias n='nvim'
