# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="agnoster"  # A clean and informative theme

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files under VCS as dirty.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time stamp shown in the history command output.
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

# Only source Oh My Zsh if it's installed
if [ -f "$ZSH/oh-my-zsh.sh" ]; then
  source $ZSH/oh-my-zsh.sh
else
  # Fallback to basic zsh setup if Oh My Zsh is not installed
  autoload -Uz compinit
  compinit
  
  # Basic prompt
  PS1='%F{green}%n@%m%f:%F{blue}%~%f$ '
  
  # Basic options
  setopt autocd
  setopt extendedglob
  setopt nomatch
  setopt notify
  unsetopt beep
  
  # Key bindings
  bindkey -e
  
  # Colors
  autoload -Uz colors
  colors
fi

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, e.g., alias zshconfig="code ~/.zshrc"
alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"

# Add custom paths
export PATH="$HOME/bin:/usr/local/bin:$PATH"

# Enable history sharing
setopt SHARE_HISTORY

# Set history file size
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# Set up fast completion
autoload -Uz compinit
compinit

# Enable syntax highlighting (using local dotfiles version)
if [ -f ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
elif [ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Enable autosuggestions (using local dotfiles version)
if [ -f ~/.zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source ~/.zsh-autosuggestions/zsh-autosuggestions.zsh
elif [ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# Set up fzf if installed
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Configure Alacritty specific settings if needed
# For example, setting up environment variables for Alacritty
export TERM="xterm-256color"

# Additional aliases
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'
alias gd='git diff'

# Development aliases
alias python='python3'
alias pip='pip3'

# Environment variables
export VISUAL=vim
export PAGER=less

# Language settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8 