# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="agnoster"  # A clean and informative theme

# Disable auto-update to speed up loading
DISABLE_AUTO_UPDATE="true"

# Disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# Enable command auto-correction
ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion
COMPLETION_WAITING_DOTS="true"

# Disable marking untracked files under VCS as dirty (speeds up git status)
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Reduced plugin list for speed - only essential plugins
plugins=(git)

# Only source Oh My Zsh if it's installed
if [ -f "$ZSH/oh-my-zsh.sh" ]; then
  source $ZSH/oh-my-zsh.sh
else
  # Fallback to basic zsh setup if Oh My Zsh is not installed
  autoload -Uz compinit
  compinit
  
  # Basic prompt
  PS1='%F{green}%n@%m%f:%F{blue}%~%f$ '
  
  # Basic options
  setopt autocd
  setopt extendedglob
  setopt nomatch
  setopt notify
  unsetopt beep
  
  # Key bindings
  bindkey -e
  
  # Colors
  autoload -Uz colors
  colors
fi

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi

# Set personal aliases, e.g., alias zshconfig="code ~/.zshrc"
alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code ~/.oh-my-zsh"

# Add custom paths
export PATH="$HOME/bin:/usr/local/bin:$PATH"

# Enable history sharing
setopt SHARE_HISTORY

# Set history file size
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# Set up fast completion
autoload -Uz compinit

# Only run compinit once per day for faster startup
# https://gist.github.com/ctechols/ca1035271be1347743137
autoload -Uz compaudit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
  compinit
  compdump
else
  compinit -C
fi

# Lazy load syntax highlighting for better performance
function load_syntax_highlighting() {
  if [ -f ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source ~/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  elif [ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
    source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  fi
}

# Lazy load autosuggestions for better performance
function load_autosuggestions() {
  if [ -f ~/.zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source ~/.zsh-autosuggestions/zsh-autosuggestions.zsh
  elif [ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
    source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  fi
}

# Load plugins after a short delay to speed up initial prompt
autoload -Uz add-zsh-hook
add-zsh-hook precmd load_syntax_highlighting
add-zsh-hook precmd load_autosuggestions

# Source custom zsh functions
[ -f ~/.zsh/alias-suggestions.zsh ] && source ~/.zsh/alias-suggestions.zsh

# Set up fzf if installed
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Configure Alacritty specific settings if needed
# For example, setting up environment variables for Alacritty
export TERM="xterm-256color"

# Additional aliases
alias ll='ls -la'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline'
alias gd='git diff'
alias gca='git commit --amend'
    ~/.zsh/alias-suggestions.zsh: src/zsh/alias-suggestions.zsh

alias gpr='echo "pushing to [$(git branch --show-current)]" && sleep 1 && git push origin $(git branch --show-current)'

alias ex='exit'
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# Development aliases
alias python='python3'
alias pip='pip3'

# Environment variables
export VISUAL=vim
export PAGER=less

# Language settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8 